### ISSUE TITLE
Weird results: no branching, just series of clusters

### ISSUE THREAD

**Issue by J-Moravec** [morrislab/pairtree#12]
I am getting very strange results from pairtree, especially compared to phyloWGS (the only soft that was able to get anything from the data).

Both pairtree and phyloWGS estimate a relatively large number of population, but paritrees finds significantly more than phyloWGS. However, there is no tree structure in the pairtree result.

Pairtree:

![weird_result](https://user-images.githubusercontent.com/10236938/116933892-4b2afb00-acb8-11eb-8a8a-bf4df6e03510.png)

PhyloWGS:

![tree](https://user-images.githubusercontent.com/10236938/116934038-85949800-acb8-11eb-860a-041d29604d34.png)

In both cases, I have used default parameters. Clustering was done through pairtree.

**Comment by dejonggr** [comment]
I also have this issue building the tree using pyclone-vi output - was there a solution posted somewhere?

**Comment by ethanumn** [comment]
Could you give an example of your output? This may or may not be the desired output depending on your data.

**Comment by dejonggr** [comment]
Feel free to close this issue again - I've revisited the problem and I think it was due to unknown artefacts leading to erroneous clustering results. The general tree structure is now consistent with my expectations.
