### ISSUE TITLE
Math behind var_read_prob

### ISSUE THREAD

**Issue by underbais** [morrislab/pairtree#17]
Hi Jeff,

So I assume it's like this: CF = VAF/var_read_prob. Correct?

If so, do I have to adjust for purity (p), i.e if my estimated var_read_prob is 0.5 then I have to multiply it by p (say 0.8) to arrive at true var_read_prob = 0.5*0.8 = 0.4 ??

Thanks
Chingiz

**Comment by ethanumn** [comment]
Hi Chingiz,

Thanks for your question. Hopefully I am able to provide a comprehensive enough answer using Jeff's thesis as my reference.

_CF_ = _VAF_/_var_read_prob_ is correct, however, adjusting for purity should not be necessary unless there is some copy number abberation  at that locus. 

Let _M_ be the average number of variant alleles in a cell, and _N_ be the population average copy number of the locus containing _M_. Using these definitions then var_read_prob can be defined as 

 _var_read_prob_ = _M_/_N_

where

_N_ = 2 + (_K_ - 2) * _p_

with _K_ being the copy number at that locus, and _p_ being the fraction of cells which have a copy number of _K_ at the locus containing _M_. _p_ is the purity of the sample if the copy number abberation is clonal. In the case of a normal copy number _K_ = 2, a single variant allele _M_ = 1, and a correct _VAF_, then _var_read_prob_ = 1/2 which should provide a good estimate of _CF_ regardless of purity.

Please let me know if any of this is unclear.

**Comment by underbais** [comment]
Great, thanks Ethan! Any chance I can access Jeff's thesis? Is it public?
