### ISSUE TITLE
(document the input files)

### ISSUE THREAD

**Issue by brucemoran** [morrislab/pairtree#2]
Hi,

I'd like to try `pairtree` but I am at a loss as to how to do so.

Can you give an example dataset, and an example command?

Thanks,

Bruce

**Comment by jwintersinger** [comment]
Hi @brucemoran,

Thanks for reaching out! I've added documentation about the input files to the [README](https://github.com/morrislab/pairtree/blob/master/README.md), and also added a [section on testing your Pairtree installation](https://github.com/morrislab/pairtree/blob/master/README.md#test-your-pairtree-installation) that provides an example dataset and command.

I will continue to update the README with more information over the coming days, but please don't hesitate to ask if you have any other questions!

**Comment by brucemoran** [comment]
Hi @jwintersinger,

thanks for getting back and updating.

Just need to know how to [cluster mutations](https://github.com/morrislab/pairtree#clustering-mutations) and them I'm all set.

BTW I have made a Singularity container which runs and passes the example data (NB needed 'plotly' installed to output html):
`singularity pull shub://brucemoran/Singularity:pairtree.centos7.mamba`

Thanks,

Bruce

**Comment by jwintersinger** [comment]
Hi @brucemoran,

You're exactly right! Typically, you should use all mutations that are of good quality. Pairtree's runtime will depend mostly on the number of clusters (i.e., subclones), not the number of mutations. I've tested with up to 10,000 mutations. The algorithm gives good results on simulated data with up to 30 subclones, and decent results at 100 subclones.

Thank you for putting together the Singularity container! I'll reference it in the README when I make my next documentation update.
