### ISSUE TITLE
decreasing the runtime for pairtree clustervars

### ISSUE THREAD

**Issue by ahgillmo** [morrislab/pairtree#22]
Hello.

I was wondering if there are any suggestions to decrease the runtime of pairtree clustervars.

I have increased the parallel count from 2-20 and have changed the --cpus-per-task (on slurm HPC) but have not decreased the runtime. Any other suggestions would be welcome. 

Thanks for your time,
Aaron

**Comment by ethanumn** [comment]
Hi Aaron -

There are a few ways you can decrease the runtime of the Pairtree `clustervars` program. Some Pairtree specific ideas to do this are:

- Set the argument `--model` equal to `linfreq`, as this clustering method does not require computing pairwise relationships before clustering can begin
- Lower the number of `--chains`  (Gibbs sampling chains)
- Lower the number of `--iterations` (number of samples each Gibbs sampling chain takes)

Changing these parameters can impact how well the clustering performs.

Please let me know if this helps,
Ethan
