### ISSUE TITLE
Annotating data from multiple timepoints + multiple regions

### ISSUE THREAD

**Issue by AnishSomani** [morrislab/pairtree#27]
Hi,

I am working with tumor data which involves multi-timepoint data which each individually consist of multi-region data. Looking at the documentation and published literature, I've seen how pairtree can be used to individually study either multiregion data or multitimepoint data individually. However, if I was to change both the timepoints and the regions, I would ideally want to annotate the timepoint. Would there be any way to do so?

**Comment by ethanumn** [comment]
Hi --

The best way to annotate the origin of a sample is by providing a sample name in your parameter file (`.params.json`) which details both its time and location. For example, if your parameter file looks as follows:

> {"samples": ["Sample 1", "Sample 2", "Sample 3"], "clusters": [], "garbage": []}

you could change the sample names to instead reflect the `Time_Location` of the samples like so

> {"samples": ["TimeA_Location1", "TimeB_Location2", "TimeC_Location3"], "clusters": [], "garbage": []}

Now when analyzing the results obtained by running Pairtree you'll be able to identify how each sample (from different time points and locations) contributed to your results.

If anything is unclear or if I misunderstood your question please let me know!

- Ethan
