### ISSUE TITLE
Calculation of Shannon index

### ISSUE THREAD

**Issue by ahgillmo** [morrislab/pairtree#30]
Hello. 

When pairtree calculates the Shannon diversity index does it use population 0 in the calculation?

**Comment by ethanumn** [comment]
Hi there -- 

Pairtree does not use population 0 (or the non-cancerous population) when calculating the Shannon diversity index. Prior to calculating any of the diversity indices, the function `_fix_eta` is called which removes population 0 and renormalizes the population frequencies for all remaining populations.
