### ISSUE TITLE
var_read_prob column in the .ssm file

### ISSUE THREAD

**Issue by pushpa-itagi** [morrislab/pairtree#31]
Hi,

I am intending to use pairtree to generate clonal evolution tress for bladder cancer samples in multiple patients. I am confused about the var_read_prob values that are needed, which indicate the CNA correction. 
1) is this probability the same as multiplicity of a mutation ? (Peter Van Loo 2021 sub-clonal reconstruction, Nature methods)?
2) Is it a probability which depends on major and minor copy numbers? So, Major CNA(Major CNA + Minor CNA).

Can you please share more information on this ? the .ssm in example folder seems to come from a diploid genome, and a lot of mutations in my dataset are not having a diploid locus.

Thanks

Regards,
Pushpa Itagi

**Comment by ethanumn** [comment]
Hi Pushpa --

I'd be glad to answer your questions. 

1. It's closely related see here: https://github.com/morrislab/pairtree/issues/17
2. Yes, it is. The issue I linked to in (1) provides more detail. 

Our newly released protocol paper provides further examples and explanations about the `.ssm` file that go beyond what's provided in the Pairtree repository readme. Please see here: https://pubmed.ncbi.nlm.nih.gov/36129821/

What might be particularly helpful in this paper is the "Before you begin" section related to _Pairtree inputs_.

Please let me know if you have any more questions.
Ethan
