### ISSUE TITLE
Contiguous variant IDs enforced?

### ISSUE THREAD

**Issue by sabackman** [morrislab/pairtree#34]
Firstly, I would like to thank you for providing the community with this wonderful tool.

I recently ran into an issue while performing som exploratory analyses on a dataset from our lab. After manually dropping a cluster I believe largely consists of poor quality variants I get the following error:

  File "[.......]/pairtree/pairtree/bin/../lib/inputparser.py", line 55, in load_ssms
    assert vids == set(range(len(variants)))
AssertionError

In the readme it is stated that "The first mutation should be assigned ID s0, with subsequent variants assigned s1, s2, .... Generally, these should be contiguous, but this is not enforced [...]"

To me it seems (if my reading of the code is correct) that the above line does indeed enforce contiguous mutation IDs. Obviously this is a minor issue and easily resolved by the end user.

Best regards
Samuel

**Comment by ethanumn** [comment]
Hi Samuel,

I'm fairly certain this assertion was meant to be taken out. I am not aware of any repercussion of doing so, and I myself have commented it out when running Pairtree. I've made the change to take it out. Thanks for spotting this!

Ethan
