### ISSUE TITLE
ValueError when plotting the tree

### ISSUE THREAD

**Issue by OumaimaHamza** [morrislab/pairtree#36]
Hi, 
I got this error when running the /bin/plotree command, 

![Screen Shot 2023-02-24 at 8 30 05 AM](https://user-images.githubusercontent.com/73792407/221190950-4fa91bae-21b3-4ffc-8ff6-b9d1d64bf801.png)
I dont understand why that's happening, since the computing and the sampling of trees worked and i got my .results.npz file and all my var_read_prob are between [0,1]

Would really appreciate your feedback on this

Thank you !

**Comment by ethanumn** [comment]
Hi there --

This is quite unusual. Is there any chance that the `var_read_prob` for one of the mutations you used is 0? I don't believe there is a check in that function that avoids dividing by a `var_read_prob` that is equal to 0, and this could very well be the issue.

Ethan

**Comment by OumaimaHamza** [comment]
Thank you so much Ethan, it works now !
