### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by SamD28** [morrislab/pairtree#38]
Hello,

Great tool, I was just wondering if this repo could have a new tag. We hope to release this software to users on our HPC however, it would be amazing to have a up-to date tag that includes this commit.

https://github.com/morrislab/pairtree/commit/0ff7173c743ebd8799bb75778a34fe4ebc631ad0

This is mostly for re-generating the tool in its current state if we were to lose our deployment image.

Thanks,
Sam

**Comment by ethanumn** [comment]
Hi Sam,

I created a new tag for the latest commit. Sorry for the delay!

Ethan
