### ISSUE TITLE
Cluster members

### ISSUE THREAD

**Issue by OumaimaHamza** [morrislab/pairtree#39]
Hi , 
In the results.html under Cluster stats we can see how many members are in each cluster, 
Is there a way to view or print-out this list of members for specific clusters ? 
Thank you !

**Comment by ethanumn** [comment]
Hi there --

Sorry for the delay in response. If you use the `bin/plottree` script you'll by default have the `VAFs (corrected)` table which shows the cluster members. You can also use the `--plot=cluster_stats` flag when running `plottree` to limit the html file to only have this table. 

If you instead wanted to do something simple like output the data for each cluster into separate files, you could use (or modify) the script attached below. 

[extract_clusters.zip](https://github.com/morrislab/pairtree/files/11748147/extract_clusters.zip)


Ethan
