### ISSUE TITLE
pairtree requires older version of numpy

### ISSUE THREAD

**Issue by agorelick** [morrislab/pairtree#40]
Hi, pairtree does not work with the latest version of numpy. This appears to be the same issue as mentioned here in the pyclone-vi github issues: https://github.com/Roth-Lab/pyclone-vi/issues/28. 

To fix this, I edited the requirements.txt file so that version 1.23.5 of numpy is used: `numpy = 1.23.5`, then re-installed:
`conda remove --name pairtree --all`
`conda create -c conda-forge -n pairtree --file requirements.txt --yes`

**Comment by oghzzang** [comment]
I'm not a developer. But I used the pairtree recently.
It worked well!
My python version is 3.11.7, and my numpy version is 1.26.3.

I installed it like you using conda. 
I think you can try to define the python version when you install conda.

**Comment by alexanderchang1** [comment]
I think it would be a good idea for the requirement.txt file to specify version number to avoid this issue. Scipy and Numba aren't updated in lockstep and these breaks will become only more common as time goes on.

**Comment by ethanumn** [comment]
I've updated the `requirements.txt` file with the latest versions that do not seem to cause any dependency issues. Please let me know if this works on your end.
