### ISSUE TITLE
how to extract number of clones per sample in results?

### ISSUE THREAD

**Issue by sahuno** [morrislab/pairtree#41]
thanks for making such a great tool, pairtree!
Que - Please is there any way to extract number of clones per sample for each patient after running pairtree?
here's example (picture) where there's 7 clones in pre_treatment and  & 6 clones in post treatment.  
https://drive.google.com/file/d/1se-ESFzUO4tdonlnfKBZBigREBQ7V_e-/view?usp=sharing

table also attached from `results.npz` file
```
'phi':
shape: (22, 7, 2)
[[[1.         1.        ]
  [0.70169436 1.        ]
  [0.47107638 0.51266541]
  [0.32137048 0.40356938]
  [0.23061798 0.26553801]
  [0.108469   0.34376056]
  [0.08538588 0.13898411]]
```

thanks in advance

**Comment by ethanumn** [comment]
Hi there --

We can use some of the utilities in the Pairtree library to find the frequency of each clone in each sample, and then use some threshold to decide whether or not that clone is present in the sample.

Here's an example of how to do this using the `example` data provided in the `/path/to/pairtree/example` folder.

```
import os, sys
import numpy as np 

# make pairtree library accessible
pairtree_path = os.path.join(os.environ["HOME"], "pairtree")
sys.path.append(os.path.join(pairtree_path, "lib"))

from util import calc_eta

# extract npz file
npz_fn = os.path.join(pairtree_path, "example", "example.results.npz")
npz = np.load(npz_fn)
structs = npz["struct"]
phi = npz["phi"]

# compute subpopulation frequency (aka 'eta') for the tree at the first index
i = 0 
eta = calc_eta(structs[i], phi[i])

# find subpopulations (i.e., clones) that are present in the samples
clones_per_sample = np.sum(np.logical_not(np.isclose(eta,0)), axis=0)
print(clones_per_sample)
```

**Comment by sahuno** [comment]
Hi @ethanumn , thanks for the demo! I'm giving it a try!

**Comment by sahuno** [comment]
it worked! thank you!

**Comment by ethanumn** [comment]
Happy to help!
