### ISSUE TITLE
Run removegarbage takes too much time?

### ISSUE THREAD

**Issue by THT-sleepy** [morrislab/pairtree#45]
Hello, I'm trying the removegarbage step.My .ssm is about 27000rows and it run out of RAM(about 60G). Then I tried to separate the .ssm file into 10 files ,however ,it run for a lot of time and still 0%?

**Comment by ethanumn** [comment]
The removegarbage script requires computing the "Pairs Tensor", and this is a very computationally expensive task. 

If your data has 27k rows, it might be better to start by removing (1) variants will low or zero VAFs across all samples and (2) those that may have been impacted by copy number changes that you are unable to accurately correct for. One way to start performing (2) is to use the [fix_bad_var_read_prob.py](https://github.com/morrislab/pairtree/blob/master/util/fix_bad_var_read_prob.py) script and use the flag `--action=add_to_garbage`. An example of how to use this script is provided in the [Pairtree STAR methods paper](https://pubmed.ncbi.nlm.nih.gov/36129821/).

Depending on how many variants are left, it's likely you'll need to cluster them. If you'd like to perform a reconstruction without clustering these variants -- we're releasing a new tool to the public in the next few weeks that is designed to handle large datasets.

**Comment by THT-sleepy** [comment]
Thank you,ethan. Actually I  have already removed variants that may be impacted by copy number changes by keeping only variants in diploid regions. However, I'm not sure whether should I remove variants lying on non-coding regions. 

My understanding is putting all variants no matter coding or not will give me a more accurate clustering result. As each cluster's peak's x coordinate(CCF or VAF) represents its corresponding subclone's frequency, this will finally give me a better estimatiton on subclonal frequency. However, removing variants lying on non-coding regions can speed the pipeline.

So my question is ,will fewer variants(like 5000) hava a significant negative impact on clustering frequency? Is it necessary to remove variants lying on non-coding regions?

Thanks again!
