### ISSUE TITLE
Manta VCFs

### ISSUE THREAD

**Issue by alexanderchang1** [morrislab/pairtree#48]
Hi, 

Does anyone in the lab have any experience trying this for Manta-called SVs? My project is specifically focusing on large structural variations. 

Thank you!

**Comment by ethanumn** [comment]
Sorry for the slow response -- I'm not aware of anyone who has applied Pairtree on structural variants. If you are able to successfully use Pairtree for this use case please let us know!

**Comment by alexanderchang1** [comment]
Hi,

I was unable to, as Manta VCF files don't convert cleanly to the necessary input required for pairtree. I do have a second question though, I work in a translational setting where many primary tumors are FFPE from the clinical archives. Have you guys done benchmarking of pairtree in terms of robustness in relation to FFPE artifacts? 

Thank you!

**Comment by ethanumn** [comment]
I do not believe we've done any benchmarking of Pairtree related to FFPE artifacts.
