### ISSUE TITLE
Error while running pairtree

### ISSUE THREAD

**Issue by itigupta2429** [morrislab/pairtree#49]
Hi Team, 
I am facing an error while running pairtree. The error is 
`"ValueError: No function 'betainc' found in __pyx_capi__ of 'scipy.special.cython_special'"`
I tried to reinstall pairtree with specifying numpy version as mentioned in this post:
[(https://github.com/morrislab/pairtree/issues/40)]
But still the error persists.
What could be the possible solution to this?
Thanks in advance!

**Comment by ethanumn** [comment]
Hi there -- 

This is an issue with the latest version of scipy. I've included in the new `requirements.txt` file a specific version that's compatible with Pairtree. Please let me know if this fixes the issue on your end.

Ethan

**Comment by itigupta2429** [comment]
Hey,
reinstalling pairtree with the updated `requirements.txt` worked for me.
Thanks for your quick response and support!
