### ISSUE TITLE
Pairtree generating nonexistent variant IDs, leading to KeyError

### ISSUE THREAD

**Issue by cathy-y** [morrislab/pairtree#52]
Hello, thanks for creating this tool! I installed Pairtree successfully using the instructions in the README, but I'm getting this error when I run it:

`Traceback (most recent call last):
  File "/home/cayan/pairtree/bin/pairtree", line 177, in <module>
    main()
  File "/home/cayan/pairtree/bin/pairtree", line 105, in main
    supervars = clustermaker.make_cluster_supervars(clusters, variants)
  File "/home/cayan/pairtree/bin/../lib/clustermaker.py", line 113, in make_cluster_supervars
    cvars = [variants[vid] for vid in cluster]
  File "/home/cayan/pairtree/bin/../lib/clustermaker.py", line 113, in <listcomp>
    cvars = [variants[vid] for vid in cluster]
KeyError: 's8341'`

It seems that it is trying to find a mutation with the ID "s8341". However, my input only has s8341 SNVs, so the IDs are contiguous from "s0" to "s8340". My ssm and parameters files are numbered in the exact same way, and neither have "s8341" as an ID. The highest numbered ID is "s8340". There are no duplicate IDs, and no overlaps in IDs across clusters. 

I'm not sure why Pairtree is generating IDs that are not in any of my inputs. 

Thanks in advance!

**Comment by cathy-y** [comment]
Some additional information, if it helps:
- Randomly removing 50 mutation IDs across the clusters in the parameters file does not change the error message, so it's not generating IDs based on the number of SNVs in the clusters. 
- Removing the first 50 mutations from the ssm file (so removing "s0" to "s49"), interestingly, changes the KeyError to "s10". "s0" to "s9" are still in the clustering parameters file, and come before "s10", so not sure why they don't trigger errors.

**Comment by ethanumn** [comment]
This error is generated precisely when a cluster in your parameter file has an ID that is not present in the ssm file. It seems like you've already checked to make sure this is true. If you Ctrl+F the ID s8431 in the parameter file you find nothing? It's possible you have some sort of formatting issue that could also be causing this.

**Comment by cathy-y** [comment]
When I Ctrl+F the offending ID in the parameter file, I find nothing. I've formatted the inputs as described, and am happy to send you the files via email so you can test it out on your end.

**Comment by ethanumn** [comment]
Interesting. If you send the ssm and parameters files I should be able to resolve this quickly.
