### ISSUE TITLE
Trees output full results

### ISSUE THREAD

**Issue by underbais** [morrislab/pairtree#6]
Hello

In PhyloWGS we get mut assignments and trees structures (e.d.summ.json) to play with:

My question is do we get just one perfect tree in Pairtree as a final result or there is away to look at all of them? If so, how? And how do I get mut assignments and tree structure out of it?

Thanks
Chingiz

**Comment by jwintersinger** [comment]
Hi Chingiz,

I should document this in the README -- thanks for reaching out! Pairtree produces multiple posterior samples, just like PhyloWGS.

* To summarize the posterior, run `bin/summposterior` (pass `--help` for usage information). This will produce a graph structure showing the different possible evolutionary relationships implied by the posterior samples, and also shows the best 20 trees.
* If you want to delve into more detail for any one of those trees, run `bin/plottree` with the `--tree-index <integer>` option. The index you pass here corresponds to the indices displayed by `summposterior` in the top 20 trees.

Please let me know if you have any other questions!

**Comment by underbais** [comment]
Hi Jeff,

Thanks a lot, very helpful. I guess my issue is with  results.npz format. In PhyloWGS mutass.zip has all mut assignments and summ.json has all tree structures. Just wonder how to extract those from npz. More info on the npz output structure would really help. 

Best,
Chingiz

**Comment by oghzzang** [comment]
Hi, I have a question related to this thread. 
Then, which mutations does the "node1" have?

**Comment by ethanumn** [comment]
Hi Hayley -

Node 0 represents the non-cancerous genome. It does not contain any of the mutations that you might have included in your analysis. We've written extensively about how to interpret the trees output by Pairtree [here](https://www.sciencedirect.com/science/article/pii/S266616672200586X#sectitle0105) and [here](https://www.sciencedirect.com/science/article/pii/S266616672200586X#sectitle0110).

Ethan

**Comment by oghzzang** [comment]
Many thanks!!!
